<?php
declare(strict_types=1);require_once dirname(__DIR__).'/config/database.php';$page_title='BanglaVerseWiki Bot API';$page_description='Authenticated API documentation for BRFA-approved article creation bots.';$page_canonical=site_url('/api/docs');require APP_ROOT.'/includes/header.php';?>
<main id="main-content" class="page-container policy-layout"><aside class="policy-sidebar"><strong>Bot API v1</strong><nav><a class="active" href="#authentication">Authentication</a><a href="#authority">Authority records</a><a href="#structured">Structured article</a><a href="#status">Job status</a></nav></aside><article class="policy-article"><header class="page-heading"><span class="eyebrow">Developer interface</span><h1>Bot Article API</h1><p>A narrow, audited API for dedicated bot accounts whose public BRFA is approved. Requests enqueue bounded jobs; the scheduler applies rate, approval, source, duplicate, and publication-mode controls.</p></header><section class="wiki-notice"><strong>No anonymous mass creation:</strong> Tokens are issued only by an administrator after community review and are shown once. Store them as secrets and revoke them after compromise.</section><section class="policy-section" id="authentication"><h2>Authentication</h2><p>Send <code>Authorization: Bearer bvw_…</code> and <code>Content-Type: application/json</code> to <code>POST /api/v1/bot/articles</code>. Tokens are hashed in MySQL, expiring, tied to one approved bot, and receive only <code>bot:articles:create</code> and/or <code>bot:authority:queue</code> when that exact capability is present in the current BRFA. Authority source IDs are also enforced separately.</p></section><section class="policy-section" id="authority"><h2>Queue a verified authority record</h2><pre class="api-example">{
  "authority_source_id": 2,
  "external_identifier": "5231190",
  "publication_mode": "pending"
}</pre><p>Enabled connectors are host-pinned and identifier-validated. Seeded source IDs are shown below; administrators should verify IDs in their installation.</p><div class="table-responsive"><table class="list-table"><thead><tr><th>ID</th><th>Authority</th><th>Identifier example</th><th>Publication policy</th></tr></thead><tbody><tr><td>1</td><td>Wikidata</td><td><code>Q42</code></td><td>Review</td></tr><tr><td>2</td><td>GBIF Species</td><td><code>5231190</code></td><td>Review</td></tr><tr><td>3</td><td>OpenAlex Works</td><td><code>W2741809807</code></td><td>Review</td></tr><tr><td>4</td><td>Crossref</td><td><code>10.1000/xyz123</code></td><td>Review</td></tr><tr><td>5</td><td>USGS Earthquakes</td><td><code>us7000abcd</code></td><td>Review</td></tr><tr><td>6</td><td>World Bank countries</td><td><code>BGD</code></td><td>Direct eligible</td></tr><tr><td>7</td><td>NASA Exoplanets</td><td><code>Kepler-22 b</code></td><td>Review</td></tr><tr><td>8</td><td>World Bank indicators</td><td><code>BGD:SP.POP.TOTL</code></td><td>Review</td></tr></tbody></table></div><p>The response is normalized into a cited infobox, facts table, provenance tag, categories, and an external identifier record. “Direct eligible” still requires explicit BRFA permission at queue and execution time; aggregate or otherwise unsuitable records are downgraded again after retrieval.</p></section><section class="policy-section" id="structured"><h2>Queue operator-supplied structured data</h2><p>This form is accepted only when the current BRFA explicitly includes the operator-supplied-payload capability.</p><pre class="api-example">{
  "title": "Example topic",
  "short_description": "A neutral description supported by the listed sources.",
  "article_type": "Place",
  "overview": "Sourced overview text.",
  "facts": "Country: Bangladesh\nDivision: Sylhet",
  "sources": "https://authority.example/record | Official record",
  "categories": "Bangladesh, Places",
  "publication_mode": "pending"
}</pre><p>Direct publication is downgraded to pending unless a fully approved (not trial) BRFA explicitly permits it. Trial jobs always require human review. Authority connectors that require a separate notability review always remain pending.</p></section><section class="policy-section" id="status"><h2>Responses and job status</h2><p>Accepted requests return HTTP 202 and a job ID. Query <code>GET /api/v1/bot/jobs/{id}</code> with the same Bearer token. Validation uses 422, authorization uses 401/403, and unknown jobs use 404.</p></section><section class="policy-help"><h2>Approval first</h2><a class="button button-primary" href="/bots/requests">Open BRFA registry</a> <a class="button" href="/policy/bots-automation">Bot policy</a></section></article></main><?php require APP_ROOT.'/includes/footer.php';
