<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/database.php';

$view = (string) ($_GET['view'] ?? 'list');
$requestId = max(0, (int) ($_GET['id'] ?? 0));
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    require_login(); verify_csrf();
    $action = (string) ($_POST['action'] ?? '');
    if($action==='submit'){
        $submissionRate=$pdo->prepare('SELECT COUNT(*) FROM bot_approval_requests WHERE requested_by=? AND created_at>DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 DAY)');$submissionRate->execute([current_user()['id']]);if((int)$submissionRate->fetchColumn()>=5){flash('error','Daily BRFA submission limit reached. Continue discussion on an existing request.');redirect('/bots/requests');}
        $name = mb_substr(trim((string) ($_POST['bot_name'] ?? '')), 0, 80);
        $task = mb_substr(trim((string) ($_POST['task_summary'] ?? '')), 0, 10000);
        $sources = mb_substr(trim((string) ($_POST['source_plan'] ?? '')), 0, 10000);
        $sample = mb_substr(trim((string) ($_POST['sample_output'] ?? '')), 0, 30000);
        $codeUrl = trim((string) ($_POST['code_url'] ?? ''));
        $rate=max(1,min(100,(int)($_POST['requested_rate']??10)));
        $requestedSourceIds=array_slice(array_values(array_unique(array_filter(array_map('intval',(array)($_POST['authority_source_ids']??[]))))),0,100);$allowedSourceIds=[];
        if($requestedSourceIds){$placeholders=implode(',',array_fill(0,count($requestedSourceIds),'?'));$sourceCheck=$pdo->prepare("SELECT id FROM authority_sources WHERE status='active' AND id IN ($placeholders)");$sourceCheck->execute($requestedSourceIds);$allowedSourceIds=array_map('intval',$sourceCheck->fetchAll(PDO::FETCH_COLUMN));sort($allowedSourceIds);}
        $allowManual=!empty($_POST['allow_manual_payload']);
        if(mb_strlen($name)<3||mb_strlen($task)<80||mb_strlen($sources)<40)flash('error','Provide a bot name, a detailed task scope, and a reliable-source plan.');
        elseif(!$allowManual&&!$allowedSourceIds)flash('error','Select at least one exact authority connector or request operator-supplied structured payloads.');
        elseif ($codeUrl !== '' && (!filter_var($codeUrl, FILTER_VALIDATE_URL) || !str_starts_with($codeUrl, 'https://'))) flash('error', 'The public code or documentation URL must use HTTPS.');
        else {
            $stmt = $pdo->prepare("INSERT INTO bot_approval_requests (requested_by,bot_name,task_summary,source_plan,sample_output,code_url,requested_rate,allowed_source_ids,allow_manual_payload,status) VALUES (?,?,?,?,?,?,?,?,?,'pending')");
            $stmt->execute([current_user()['id'],$name,$task,$sources,$sample?:null,$codeUrl?:null,$rate,$allowedSourceIds?implode(',',$allowedSourceIds):null,$allowManual?1:0]);
            $id = (int) $pdo->lastInsertId();
            log_activity($pdo, 'bot.brfa_submitted', 'bot_approval_request', $id);
            flash('success', 'BRFA submitted for community review. The bot cannot operate until approved.'); redirect('/bots/request/' . $id);
        }
    } elseif ($action === 'comment') {
        $id = (int) ($_POST['request_id'] ?? 0);
        $body = mb_substr(trim((string) ($_POST['body'] ?? '')), 0, 10000);
        $position = in_array($_POST['position'] ?? '', ['comment','support','oppose','question'], true) ? $_POST['position'] : 'comment';
        $exists=$pdo->prepare('SELECT 1 FROM bot_approval_requests WHERE id=?');$exists->execute([$id]);
        if(!$exists->fetchColumn()){flash('error','BRFA not found.');redirect('/bots/requests');}
        $commentRate=$pdo->prepare('SELECT COUNT(*) FROM bot_approval_comments WHERE user_id=? AND created_at>DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 MINUTE)');$commentRate->execute([current_user()['id']]);if((int)$commentRate->fetchColumn()>=5){flash('error','Comment rate limit reached. Wait one minute.');redirect('/bots/request/'.$id);}
        if (mb_strlen($body) < 5) flash('error', 'Write a substantive comment.');
        else { $pdo->prepare('INSERT INTO bot_approval_comments (request_id, user_id, position, body) VALUES (?, ?, ?, ?)')->execute([$id, current_user()['id'], $position, $body]); log_activity($pdo, 'bot.brfa_commented', 'bot_approval_request', $id, ['position' => $position]); flash('success', 'Your BRFA comment was added.'); }
        redirect('/bots/request/' . $id);
    } elseif ($action === 'review') {
        if (!is_admin()) { http_response_code(403); exit('Administrator access required.'); }
        $id = (int) ($_POST['request_id'] ?? 0);
        $decision = in_array($_POST['decision'] ?? '', ['approved','trial','rejected','revoked'], true) ? $_POST['decision'] : 'rejected';
        $notes=mb_substr(trim((string)($_POST['closing_notes']??'')),0,10000);if(mb_strlen($notes)<20){flash('error','Provide a substantive closing rationale of at least 20 characters.');redirect('/bots/request/'.$id);}
        $pdo->beginTransaction();$stmt=$pdo->prepare('SELECT * FROM bot_approval_requests WHERE id=? FOR UPDATE');$stmt->execute([$id]);$request=$stmt->fetch();
        if(!$request){$pdo->rollBack();flash('error','BRFA not found.');redirect('/bots/requests');}
        $botId = (int) ($request['bot_id'] ?? 0);
        if (in_array($decision, ['approved','trial'], true)) {
            if (!$botId) {
                $baseSlug=mb_substr(slugify($request['bot_name'])?:'approved-bot',0,70); $slug=$baseSlug; $suffix=0;
                $find = $pdo->prepare('SELECT 1 FROM bots WHERE slug = ?');$find->execute([$slug]);
                while($find->fetchColumn()){$suffix++;$slug=$baseSlug.'-brfa-'.$id.($suffix>1?'-'.$suffix:'');$find->execute([$slug]);}
                $pdo->prepare("INSERT INTO bots (name,slug,description,status,created_by,daily_limit) VALUES (?,?,?,'active',?,?)")->execute([$request['bot_name'],$slug,excerpt($request['task_summary'],480),$request['requested_by'],min(100,(int)$request['requested_rate'])]);$botId=(int)$pdo->lastInsertId();$pdo->prepare('UPDATE bot_approval_requests SET bot_id=? WHERE id=?')->execute([$botId,$id]);
            }
            $botUser = $pdo->prepare('SELECT user_id FROM bots WHERE id = ?'); $botUser->execute([$botId]); $botUserId = (int) ($botUser->fetchColumn() ?: 0);
            if (!$botUserId) {
                $username = mb_substr(preg_replace('/[^\p{L}\p{N}_-]+/u', '_', $request['bot_name']) ?: 'ApprovedBot',0,25);
                $username.='_bot_'.$botId;
                $pdo->prepare("INSERT INTO users (username, email, password_hash, role, status) VALUES (?, ?, ?, 'bot', 'active')")->execute([$username, 'bot-' . $botId . '@internal.invalid', password_hash(bin2hex(random_bytes(32)), PASSWORD_DEFAULT)]);
                $botUserId = (int) $pdo->lastInsertId();
                $pdo->prepare('UPDATE bots SET user_id = ? WHERE id = ?')->execute([$botUserId, $botId]);
            }
            $pdo->prepare("UPDATE bots SET status = 'active', daily_limit = ? WHERE id = ?")->execute([min(100, (int) $request['requested_rate']), $botId]);
        } elseif ($botId) { $pdo->prepare("UPDATE bots SET status='paused' WHERE id=?")->execute([$botId]);$pdo->prepare("UPDATE bot_jobs SET status='cancelled',completed_at=UTC_TIMESTAMP(),error_message='BRFA approval withdrawn.' WHERE bot_id=? AND status='queued'")->execute([$botId]);$pdo->prepare("UPDATE api_tokens SET revoked_at=UTC_TIMESTAMP() WHERE bot_id=? AND revoked_at IS NULL")->execute([$botId]); }
        $trialExpiry=$decision==='trial'?gmdate('Y-m-d H:i:s',time()+30*86400):null;
        $allowDirect=$decision==='approved'&&!empty($_POST['allow_direct_publish'])?1:0;
        $pdo->prepare('UPDATE bot_approval_requests SET bot_id=?,status=?,closing_notes=?,reviewed_by=?,allow_direct_publish=?,trial_expires_at=? WHERE id=?')->execute([$botId?:null,$decision,$notes?:null,current_user()['id'],$allowDirect,$trialExpiry,$id]);
        log_activity($pdo,'bot.brfa_'.$decision,'bot_approval_request',$id,['bot_id'=>$botId,'allow_direct_publish'=>$allowDirect,'trial_expires_at'=>$trialExpiry,'closing_notes'=>$notes]);$pdo->commit();
        flash('success', 'BRFA decision recorded and bot permissions synchronized.'); redirect('/bots/request/' . $id);
    } elseif ($action === 'issue_token') {
        if (!is_admin()) { http_response_code(403); exit('Administrator access required.'); }
        $botId=(int)($_POST['bot_id']??0);$pdo->beginTransaction();
        $stmt=$pdo->prepare("SELECT b.user_id,br.id AS approval_request_id,br.allowed_source_ids,br.allow_manual_payload FROM bots b JOIN bot_approval_requests br ON br.id=(SELECT MAX(br2.id) FROM bot_approval_requests br2 WHERE br2.bot_id=b.id) WHERE b.id=? AND b.status='active' AND br.status IN ('approved','trial') AND (br.status='approved' OR (br.status='trial' AND br.trial_expires_at>UTC_TIMESTAMP())) ORDER BY br.id DESC LIMIT 1 FOR UPDATE");$stmt->execute([$botId]);$tokenApproval=$stmt->fetch();$userId=(int)($tokenApproval['user_id']??0);
        if(!$userId){$pdo->rollBack();flash('error','Only an approved active bot can receive an API token.');}
        else {
            $scopeList=[];if(!empty($tokenApproval['allow_manual_payload']))$scopeList[]='bot:articles:create';if(!empty($tokenApproval['allowed_source_ids']))$scopeList[]='bot:authority:queue';if(!$scopeList){$pdo->rollBack();flash('error','The current BRFA has no machine-readable API scope.');redirect('/bots/request/'.(int)($_POST['request_id']??0));}
            $plain='bvw_'.bin2hex(random_bytes(32));$prefix=substr($plain,0,12);$scopeString=implode(',',$scopeList);
            $pdo->prepare("INSERT INTO api_tokens (user_id,bot_id,approval_request_id,created_by,token_name,token_prefix,token_hash,scopes,expires_at) VALUES (?,?,?,?,'Article creation API',?,?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 1 YEAR))")->execute([$userId,$botId,$tokenApproval['approval_request_id'],current_user()['id'],$prefix,hash('sha256',$plain),$scopeString]);
            $_SESSION['new_bot_token']=$plain;log_activity($pdo,'bot.api_token_issued','bot',$botId,['brfa_id'=>(int)$tokenApproval['approval_request_id']]);$pdo->commit();flash('success', 'API token created. Copy it now; it will not be shown again.');
        }
        redirect('/bots/request/' . (int) ($_POST['request_id'] ?? 0));
    } elseif ($action === 'revoke_token') {
        if(!is_admin()){http_response_code(403);exit('Administrator access required.');}
        $tokenId=(int)($_POST['token_id']??0);$requestId=(int)($_POST['request_id']??0);
        $revoke=$pdo->prepare('UPDATE api_tokens t JOIN bot_approval_requests br ON br.bot_id=t.bot_id SET t.revoked_at=UTC_TIMESTAMP() WHERE t.id=? AND br.id=? AND t.revoked_at IS NULL');$revoke->execute([$tokenId,$requestId]);
        log_activity($pdo,'bot.api_token_revoked','api_token',$tokenId,['brfa_id'=>$requestId]);flash('success','API token revoked.');redirect('/bots/request/'.$requestId);
    }
}

if($view==='new'){
    require_login();$availableSources=$pdo->query("SELECT id,name,description,license_name,publication_policy FROM authority_sources WHERE status='active' ORDER BY name")->fetchAll(); $page_title = 'Request bot approval — ' . SITE_NAME; $page_robots = 'noindex,follow'; require APP_ROOT . '/includes/header.php'; ?>
    <main id="main-content" class="page-narrow"><header class="page-heading"><span class="eyebrow">Bot Requests for Approval</span><h1>Request bot approval</h1><p>Automation must be narrow, transparent, source-backed, technically reversible, and community reviewed before any autonomous edits.</p></header><form class="panel panel-body" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="submit"><div class="form-group"><label>Proposed bot name</label><input name="bot_name" maxlength="80" required></div><div class="form-group"><label>Exact tasks and safeguards</label><textarea name="task_summary" rows="8" minlength="80" required placeholder="Describe every edit type, notability test, error handling, test plan, and stop condition."></textarea></div><div class="form-group"><label>Authority data and sourcing plan</label><textarea name="source_plan" rows="6" minlength="40" required placeholder="Name each external database, license, identifiers, fields, and how records establish notability."></textarea></div><fieldset class="form-group"><legend>Exact machine scope requested</legend><div class="authority-scope-list"><?php foreach($availableSources as $source):?><label class="checkbox"><input type="checkbox" name="authority_source_ids[]" value="<?=(int)$source['id']?>"><span><strong><?=e($source['name'])?></strong><small><?=e($source['license_name'])?> · <?=e($source['publication_policy']==='direct'?'direct eligible with approval':'review required')?></small></span></label><?php endforeach;?></div><label class="checkbox"><input type="checkbox" name="allow_manual_payload" value="1"> Permit operator-supplied structured payloads with HTTPS citations</label></fieldset><div class="form-group"><label>Sample wiki output</label><textarea name="sample_output" rows="8"></textarea></div><div class="form-row"><div><label>Public code or documentation URL</label><input type="url" name="code_url" placeholder="https://"></div><div><label>Maximum articles per day</label><input type="number" name="requested_rate" min="1" max="100" value="10"></div></div><button class="button button-primary" type="submit">Submit public BRFA</button></form></main><?php require APP_ROOT . '/includes/footer.php'; exit;
}

if ($view === 'detail') {
    $stmt = $pdo->prepare("SELECT br.*, u.username, reviewer.username AS reviewer_name, b.status AS bot_status FROM bot_approval_requests br JOIN users u ON u.id = br.requested_by LEFT JOIN users reviewer ON reviewer.id = br.reviewed_by LEFT JOIN bots b ON b.id = br.bot_id WHERE br.id = ?"); $stmt->execute([$requestId]); $request = $stmt->fetch();
    if(!$request){http_response_code(404);exit('BRFA not found.');}
    $approvedSourceIds=array_values(array_filter(array_map('intval',explode(',',(string)($request['allowed_source_ids']??'')))));$approvedSources=[];if($approvedSourceIds){$sourcePlaceholders=implode(',',array_fill(0,count($approvedSourceIds),'?'));$sourceNames=$pdo->prepare("SELECT id,name FROM authority_sources WHERE id IN ($sourcePlaceholders) ORDER BY name");$sourceNames->execute($approvedSourceIds);$approvedSources=$sourceNames->fetchAll();}
    $comments = $pdo->prepare("SELECT c.*, u.username FROM bot_approval_comments c JOIN users u ON u.id = c.user_id WHERE c.request_id = ? AND c.status = 'visible' ORDER BY c.id"); $comments->execute([$requestId]); $comments = $comments->fetchAll();
    $tokens=[];if(is_admin()&&!empty($request['bot_id'])){$tokenQuery=$pdo->prepare('SELECT id,token_name,token_prefix,scopes,last_used_at,expires_at,revoked_at,created_at FROM api_tokens WHERE bot_id=? ORDER BY id DESC');$tokenQuery->execute([$request['bot_id']]);$tokens=$tokenQuery->fetchAll();}
    $page_title = 'BRFA ' . $requestId . ': ' . $request['bot_name'] . ' — ' . SITE_NAME; $page_description = excerpt($request['task_summary'], 220); $page_no_store=true; require APP_ROOT . '/includes/header.php';
    $newToken = $_SESSION['new_bot_token'] ?? null; unset($_SESSION['new_bot_token']); ?>
    <main id="main-content" class="page-container brfa-page"><header class="page-heading"><span class="eyebrow">Bot Request for Approval #<?= $requestId ?></span><h1><?= e($request['bot_name']) ?></h1><p>Proposed by <a href="/user/<?= rawurlencode($request['username']) ?>"><?= e($request['username']) ?></a> · <span class="badge badge-<?= in_array($request['status'], ['approved','trial'], true) ? 'active' : ($request['status'] === 'rejected' ? 'blocked' : 'pending') ?>"><?= e($request['status']) ?></span></p></header>
    <?php if ($newToken): ?><div class="token-reveal"><strong>Copy this API token now</strong><code><?= e($newToken) ?></code><p>It is stored only as a SHA-256 hash and cannot be recovered.</p></div><?php endif; ?>
    <div class="admin-two-column"><article class="panel panel-body"><h2>Task scope</h2><p class="pre-wrap"><?= e($request['task_summary']) ?></p><h2>Authority sources and notability</h2><p class="pre-wrap"><?= e($request['source_plan']) ?></p><?php if ($request['sample_output']): ?><h2>Sample output</h2><pre class="brfa-sample"><?= e($request['sample_output']) ?></pre><?php endif; ?><?php if ($request['code_url']): ?><p><a href="<?= e($request['code_url']) ?>" rel="nofollow noopener">Public implementation documentation ↗</a></p><?php endif; ?><dl class="article-facts"><dt>Requested rate</dt><dd><?=(int)$request['requested_rate']?> per day</dd><dt>Machine scopes</dt><dd><?= $request['allow_manual_payload']?'Operator-supplied structured payloads'.($approvedSources?' · ':''):''?><?= $approvedSources?e(implode(', ',array_column($approvedSources,'name'))):(!$request['allow_manual_payload']?'No valid connector recorded':'')?></dd><dt>Direct publication</dt><dd><?= $request['status']==='approved'&&$request['allow_direct_publish']?'Explicitly permitted where source policy also allows it':'No — human review required' ?></dd><?php if($request['trial_expires_at']):?><dt>Trial expires</dt><dd><?=time_tag($request['trial_expires_at'],false)?></dd><?php endif;?><?php if ($request['closing_notes']): ?><dt>Closing decision</dt><dd><?= e($request['closing_notes']) ?></dd><?php endif; ?></dl></article><aside class="panel panel-body"><h2>Approval standard</h2><ol><li>Clear community benefit and non-duplicative scope</li><li>Reliable authority database and compatible license</li><li>Notability rule for every generated page</li><li>Bounded rate, dry run, monitoring, and emergency stop</li><li>Neutral templates and traceable citations</li></ol><a href="/policy/bots-automation">Full bot policy →</a></aside></div>
    <section class="panel" style="margin-top:20px"><div class="panel-header"><h2>Community review</h2><span><?= count($comments) ?> comments</span></div><div class="panel-body discussion-list"><?php foreach ($comments as $comment): ?><article class="discussion"><div class="discussion-avatar"><?= e(mb_strtoupper(mb_substr($comment['username'],0,1))) ?></div><div class="discussion-body"><header><strong><?= e($comment['username']) ?> · <?= e($comment['position']) ?></strong><time data-utc-time="<?= e(utc_iso($comment['created_at'])) ?>"><?= e($comment['created_at']) ?> UTC</time></header><p><?= e($comment['body']) ?></p></div></article><?php endforeach; ?><?php if (is_logged_in()): ?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="comment"><input type="hidden" name="request_id" value="<?= $requestId ?>"><div class="form-row"><div><label>Position</label><select name="position"><option value="comment">Comment</option><option value="support">Support</option><option value="oppose">Oppose</option><option value="question">Question</option></select></div><div><label>Policy-based reasoning</label><textarea name="body" rows="4" required></textarea></div></div><button class="button" type="submit">Add review comment</button></form><?php endif; ?></div></section>
    <?php if (is_admin()): ?><section class="panel panel-body" style="margin-top:20px"><h2>Administrator closure</h2><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="review"><input type="hidden" name="request_id" value="<?= $requestId ?>"><div class="form-row"><div><label>Decision</label><select name="decision"><option value="trial">30-day trial</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="revoked">Revoke approval</option></select></div><label class="checkbox"><input type="checkbox" name="allow_direct_publish" value="1"> Permit direct publication after successful trial</label></div><label>Closing rationale</label><textarea name="closing_notes" rows="4" required></textarea><button class="button button-primary" type="submit">Record decision</button></form><?php if ($request['bot_id'] && in_array($request['status'], ['approved','trial'], true)): ?><form method="post" style="margin-top:12px"><?= csrf_field() ?><input type="hidden" name="action" value="issue_token"><input type="hidden" name="request_id" value="<?= $requestId ?>"><input type="hidden" name="bot_id" value="<?= (int) $request['bot_id'] ?>"><button class="button" type="submit" data-confirm="Issue a new one-time API token?">Issue API token</button></form><?php endif; ?><?php if($tokens):?><h3>Issued credentials</h3><div class="token-list"><?php foreach($tokens as $token):?><article><code><?=e($token['token_prefix'])?>…</code><span><?=e($token['scopes'])?><br>Expires <?=time_tag($token['expires_at'],false)?> · <?= $token['last_used_at']?'last used '.time_tag($token['last_used_at']):'never used'?></span><?php if(!$token['revoked_at']):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="revoke_token"><input type="hidden" name="request_id" value="<?=$requestId?>"><input type="hidden" name="token_id" value="<?=(int)$token['id']?>"><button class="button button-quiet" type="submit" data-confirm="Revoke this API token immediately?">Revoke</button></form><?php else:?><span class="badge badge-blocked">Revoked</span><?php endif;?></article><?php endforeach;?></div><?php endif;?></section><?php endif; ?></main><?php require APP_ROOT . '/includes/footer.php'; exit;
}

$requests = $pdo->query("SELECT br.*, u.username, (SELECT COUNT(*) FROM bot_approval_comments c WHERE c.request_id = br.id AND c.status = 'visible') AS comments FROM bot_approval_requests br JOIN users u ON u.id = br.requested_by ORDER BY CASE br.status WHEN 'pending' THEN 0 WHEN 'trial' THEN 1 ELSE 2 END, br.id DESC LIMIT 100")->fetchAll();
$page_title = 'Bot requests for approval — ' . SITE_NAME; $page_description = 'Public review and approval of BanglaVerseWiki automation tasks.'; require APP_ROOT . '/includes/header.php'; ?>
<main id="main-content" class="page-container"><header class="page-heading"><span class="eyebrow">Automation governance</span><h1>Bot Requests for Approval</h1><p>Every autonomous bot must disclose its code, sources, templates, rate, notability rules, and safeguards. Community discussion precedes administrator closure.</p><div class="form-actions"><?php if (is_logged_in()): ?><a class="button button-primary" href="/bots/request/new">Request approval</a><?php endif; ?><a class="button" href="/policy/bots-automation">Bot policy</a><a class="button" href="/api/docs">Bot API documentation</a></div></header><div class="policy-card-grid"><?php foreach ($requests as $request): ?><a class="policy-card" href="/bots/request/<?= (int) $request['id'] ?>"><span class="card-kicker">BRFA #<?= (int) $request['id'] ?> · <?= e($request['status']) ?></span><h2><?= e($request['bot_name']) ?></h2><p><?= e(excerpt($request['task_summary'], 180)) ?></p><span><?= e($request['username']) ?> · <?= (int) $request['comments'] ?> comments →</span></a><?php endforeach; ?><?php if (!$requests): ?><div class="empty-state"><h2>No bot requests yet</h2><p>The automation registry is ready for its first transparent proposal.</p></div><?php endif; ?></div></main>
<?php require APP_ROOT . '/includes/footer.php';
