<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/database.php';
require_once APP_ROOT . '/includes/PolicyCatalog.php';

$stats = $pdo->query("SELECT
    (SELECT COUNT(*) FROM articles WHERE status = 'published') AS articles,
    (SELECT COUNT(*) FROM users WHERE status = 'active') AS users,
    (SELECT COUNT(*) FROM revisions) AS edits,
    (SELECT COUNT(*) FROM discussions WHERE status = 'visible') AS discussions,
    (SELECT COUNT(*) FROM articles WHERE status = 'pending') AS pending,
    (SELECT COUNT(*) FROM bot_jobs WHERE status = 'queued') AS bot_jobs")->fetch();
$recentChanges = $pdo->query("SELECT r.created_at, r.edit_summary, r.is_minor, a.title, a.slug, u.username
    FROM revisions r JOIN articles a ON a.id = r.article_id LEFT JOIN users u ON u.id = r.user_id
    WHERE a.status = 'published' ORDER BY r.id DESC LIMIT 10")->fetchAll();
$activeEditors = $pdo->query("SELECT u.username, u.role, COUNT(r.id) AS edits, MAX(r.created_at) AS last_edit
    FROM users u JOIN revisions r ON r.user_id = u.id
    WHERE u.status = 'active' AND r.created_at >= DATE_SUB(UTC_TIMESTAMP(), INTERVAL 30 DAY)
    GROUP BY u.id, u.username, u.role ORDER BY edits DESC, last_edit DESC LIMIT 8")->fetchAll();
$wantedPages = $pdo->query("SELECT target_title, COUNT(*) AS links FROM article_links WHERE target_article_id IS NULL GROUP BY target_key, target_title ORDER BY links DESC, target_title LIMIT 10")->fetchAll();
$recentTalk = $pdo->query("SELECT d.body, d.created_at, a.title, a.slug, u.username FROM discussions d JOIN articles a ON a.id = d.article_id LEFT JOIN users u ON u.id = d.user_id WHERE d.status = 'visible' AND a.status = 'published' ORDER BY d.id DESC LIMIT 6")->fetchAll();
$zeroSearches = can_moderate() ? $pdo->query("SELECT normalized_query, COUNT(*) AS searches FROM search_queries WHERE result_count = 0 AND created_at >= DATE_SUB(UTC_TIMESTAMP(), INTERVAL 30 DAY) GROUP BY normalized_query ORDER BY searches DESC LIMIT 8")->fetchAll() : [];
$page_title = 'Community portal — ' . SITE_NAME;
$page_description = 'Coordinate editing, find missing articles, discuss improvements, learn policies, and follow community activity on BanglaVerseWiki.';
$page_canonical = site_url('/community');
require APP_ROOT . '/includes/header.php';
?>
<main id="main-content" class="page-container community-portal">
<header class="community-hero"><div><span class="eyebrow">Build knowledge together</span><h1>Community portal</h1><p>A working center for editors, readers, moderators, and administrators. Find useful tasks, coordinate improvements, and learn the standards behind every article.</p><div class="form-actions"><?php if (is_logged_in()): ?><a class="button button-primary" href="/create">Create an article</a><a class="button" href="/drafts">Open my workspace</a><?php else: ?><a class="button button-primary" href="/register">Join the community</a><a class="button" href="/login">Sign in</a><?php endif; ?><a class="button" href="/policies">Read policies</a></div></div><div class="community-mark" aria-hidden="true"><span>ব</span><small>Knowledge grows through review</small></div></header>
<section class="community-stats" aria-label="Community statistics"><div><strong><?= format_number($stats['articles']) ?></strong><span>published articles</span></div><div><strong><?= format_number($stats['edits']) ?></strong><span>saved revisions</span></div><div><strong><?= format_number($stats['users']) ?></strong><span>active accounts</span></div><div><strong><?= format_number($stats['discussions']) ?></strong><span>talk contributions</span></div></section>
<div class="community-grid">
<section class="panel community-tasks"><div class="panel-header"><h2>Contribute now</h2><span>Choose a useful task</span></div><div class="portal-action-grid"><a href="/create"><strong>Start a sourced article</strong><span>Use the visual or source editor and submit for review.</span></a><a href="/special/recent"><strong>Review recent changes</strong><span>Check new edits for sources, neutrality, and clarity.</span></a><a href="/categories"><strong>Improve a topic area</strong><span>Browse categories and connect related knowledge.</span></a><a href="/policy/editing-style"><strong>Copyedit and format</strong><span>Improve structure, links, accessibility, and citations.</span></a></div></section>
<section class="panel"><div class="panel-header"><h2>Most-wanted pages</h2><a href="/special/wanted">View all</a></div><?php if ($wantedPages): ?><nav class="wanted-list"><?php foreach ($wantedPages as $wanted): ?><a href="/create?title=<?= rawurlencode($wanted['target_title']) ?>"><strong><?= e($wanted['target_title']) ?></strong><span><?= format_number($wanted['links']) ?> incoming link<?= (int) $wanted['links'] === 1 ? '' : 's' ?></span></a><?php endforeach; ?></nav><?php else: ?><div class="empty-state">Wanted pages appear as editors add internal links to topics that do not exist yet.</div><?php endif; ?></section>
<section class="panel"><div class="panel-header"><h2>Recent community changes</h2><a href="/special/recent">View all</a></div><?php if ($recentChanges): ?><div class="portal-feed"><?php foreach ($recentChanges as $change): ?><article><a href="/wiki/<?= e($change['slug']) ?>"><strong><?= e($change['title']) ?></strong></a><p><?= e($change['edit_summary'] ?: 'Improved article') ?><?= $change['is_minor'] ? ' · minor edit' : '' ?></p><small><?= e($change['username'] ?: 'System') ?> · <?= e(time_ago($change['created_at'])) ?></small></article><?php endforeach; ?></div><?php else: ?><div class="empty-state">The fresh encyclopedia is ready for its first contribution.</div><?php endif; ?></section>
<section class="panel"><div class="panel-header"><h2>Active editors</h2><span>Last 30 days</span></div><?php if ($activeEditors): ?><div class="editor-leaderboard"><?php foreach ($activeEditors as $index => $editor): ?><a href="/user/<?= rawurlencode($editor['username']) ?>"><span class="rank"><?= $index + 1 ?></span><span><strong><?= e($editor['username']) ?></strong><small><?= e(ucfirst($editor['role'])) ?> · last edit <?= e(time_ago($editor['last_edit'])) ?></small></span><b><?= format_number($editor['edits']) ?></b></a><?php endforeach; ?></div><?php else: ?><div class="empty-state">Active editors will appear after contributions begin.</div><?php endif; ?></section>
<section class="panel"><div class="panel-header"><h2>Recent talk</h2><span>Article discussions</span></div><?php if ($recentTalk): ?><div class="portal-feed compact"><?php foreach ($recentTalk as $talk): ?><article><a href="/talk/<?= e($talk['slug']) ?>"><strong><?= e($talk['title']) ?></strong></a><p><?= e(excerpt($talk['body'], 110)) ?></p><small><?= e($talk['username'] ?: 'Editor') ?> · <?= e(time_ago($talk['created_at'])) ?></small></article><?php endforeach; ?></div><?php else: ?><div class="empty-state">Use an article’s Talk tab to discuss improvements and sources.</div><?php endif; ?></section>
<section class="panel"><div class="panel-header"><h2>Governance and safety</h2><a href="/policies">All policies</a></div><nav class="governance-links"><a href="/policy/founding-principles">Founding principles</a><a href="/policy/neutral-point-of-view">Neutral point of view</a><a href="/policy/verifiability">Verifiability</a><a href="/policy/living-people">Living people</a><a href="/policy/copyright-licensing">Copyright and licensing</a><a href="/policy/dispute-resolution">Dispute resolution</a><a href="/policy/bots-automation">Bots and automation</a><a href="/policy/administrator-accountability">Administrator accountability</a></nav></section>
<?php if ($zeroSearches): ?><section class="panel"><div class="panel-header"><h2>Reader knowledge gaps</h2><span>Moderator view</span></div><nav class="wanted-list"><?php foreach ($zeroSearches as $missing): ?><a href="/create?title=<?= rawurlencode($missing['normalized_query']) ?>"><strong><?= e($missing['normalized_query']) ?></strong><span><?= format_number($missing['searches']) ?> searches</span></a><?php endforeach; ?></nav></section><?php endif; ?>
<section class="panel"><div class="panel-header"><h2>Automation transparency</h2><span><?= format_number($stats['bot_jobs']) ?> queued jobs</span></div><div class="panel-body"><p>BanglaVerseBot can structure administrator-supplied facts and source links. Jobs are bounded, audited, labeled, and default to human review. Automation never replaces source verification or community correction.</p><a href="/policy/bots-automation">Read the bot policy →</a></div></section>
</div>
</main>
<script type="application/ld+json"><?= json_encode(['@context' => 'https://schema.org', '@type' => 'CollectionPage', 'name' => 'BanglaVerseWiki Community Portal', 'description' => $page_description, 'url' => $page_canonical, 'about' => ['@type' => 'Organization', 'name' => SITE_NAME]], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_HEX_TAG) ?></script>
<?php require APP_ROOT . '/includes/footer.php'; ?>
